apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptocurrencies-service-deployment
  labels:
    app: cryptocurrencies-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cryptocurrencies-service
  template:
    metadata:
      labels:
        app: cryptocurrencies-service
    spec:
      containers:
      - name: cryptocurrencies-service
        image: cryptocurrencies_service
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: TZ
          value: "America/Toronto"
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - name: timezone
          mountPath: /etc/timezone
        args:
        - bash
        - -c
        - "python -m uvicorn src.app.main:app --host 0.0.0.0 --port 8000"
      volumes:
      - name: timezone
        hostPath:
          path: /usr/share/zoneinfo/America/Toronto
