apiVersion: v1
kind: Service
metadata:
  name: cryptocurrencies-service
  labels:
    app: cryptocurrencies-service
spec:
  selector:
    app: cryptocurrencies-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP # Change to NodePort or LoadBalancer if external access is needed
